export const data = [
  { id: 1,
    img: '../images/person-1.jpeg',
    name: 'Bertie Yates',
    age: 29},
  { id: 2,
    img: '../images/person-2.jpeg',
    name: 'Hester Hogan',
    age: 32},
  { id: 3,
    img: '../images/person-3.jpeg',
    name: 'Larry Little',
    age: 36 },
  { id: 4,
    img: '../images/person-4.jpeg',
    name: 'Sean Walsh',
    age: 34},
  { id: 5,
    img: '../images/person-5.jpeg',
    name: 'Lola Gardner',
    age: 29 },
]

